CREATE TABLE IF NOT EXISTS binaries (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `mimetype` VARCHAR(100) NOT NULL,
  `data` LONGBLOB,
  `creationdate` DATETIME NOT NULL,
  `modificationdate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;