<?php
/**
 * @defgroup YAML4
 * @ingroup CSS
 * 
 * Basic installation of YAML CSS framework, Version 4.
 * 
 * @see http://www.yaml.de/en/
 *
 * This is a drop in replacement for the css.yaml module that covers YAML 3.2. However, the layout
 * must be adjusted, see http://www.yaml.de/download/YAML4-migration-cheat-sheet.pdf
 *
 * By default this module renders HTML 5 code.
 * 
 * @section Usage Usage
 * 
 * The module copies YAML css to the app/www directory. Core YAML files are overwritten on 
 * each systemupdate, while files below /app/www/css/ are only copied once. *
 * 
 * By default a 213-template is installed. Use the YAML builder to create your own template
 * and CSS stubs: http://builder.yaml.de/
 *
 * For YAML licencing see http://www.yaml.de/license.html.
 *
 * @section Forms Forms
 * 
 * @see http://www.yaml.de/en/documentation/css-components/form-construction-kit.html
 * 
 * Set APP_YAML_USE_FORMS to true to have the YAML module change the HTML of generated input
 * widgets to a YAML compatible style.
 * 
 * If forms are enabled in YAML module you should include the YAML forms CSS file. There are two of them 
 * to choose:
 * 
 * - /css/screen/forms.css: This file works on the form tag directly, so it is compatible with forms
 *   of existing modules.
 * - /yaml/screen/forms.css: This is the original YAML forms file, and requires a class "yforms" to be set on the
 *   form element. This is not compatible with forms generated by other modules.
 */

EventSource::Instance()->register(new CSSYaml4EventSink());

/**
 * Config for CSS YAML module
 * 
 * @author Gerd Riesselmann
 * @ingroup YAML
 */
class ConfigYAML4 {
	const VERSION = 'YAML4_VERSION';
	const USE_FORMS = 'YAML4_USE_FORMS';
}

Config::set_value_from_constant(ConfigYAML4::VERSION, 'APP_YAML4_VERSION', '4.0');
Config::set_feature_from_constant(ConfigYAML4::USE_FORMS, 'APP_YAML_USE_FORMS', false);


