<?php
/**
 * @defgroup YAML
 * @ingroup CSS
 * 
 * Basic installation of YAML CSS framework.
 * 
 * @see http://www.yaml.de/en/
 * 
 * @section Usage Usage
 * 
 * The module copies YAML css to the app/www directory. Core YAML files are overwritten on 
 * each systemupdate, while files below /app/www/css/ are only copied once.
 * 
 * 
 * By default a 213-template is installed. Use the YAML builder to create your own template
 * and CSS stubs: http://builder.yaml.de/ 
 *
 * @section Forms Forms
 * 
 * @see http://www.yaml.de/en/documentation/css-components/form-construction-kit.html
 * 
 * Set APP_YAML_USE_FORMS to true to have the YAML module change the HTML of generated input
 * widgets to a YAML compatible style.
 * 
 * If forms are enabled in YAML module you should include the YAML forms CSS file. There are two of them 
 * to choose:
 * 
 * - /css/screen/forms.css: This file works on the form tag directly, so it is compatible with forms
 *   of existing modules.
 * - /yaml/screen/forms.css: This is the original YAML forms file, and requires a class "yforms" to be set on the
 *   form element. This is not compatible with forms generated by other modules.
 */

EventSource::Instance()->register(new CSSYamlEventSink());

/**
 * Config for CSS YAML module
 * 
 * @author Gerd Riesselmann
 * @ingroup YAML
 */
class ConfigYAML {
	const YAML_VERSION = 'YAML_VERSION';
	const YAML_USE_FORMS = 'YAML_USE_FORMS';
}

Config::set_value_from_constant(ConfigYAML::YAML_VERSION, 'APP_YAML_VERSION', '3.2');
Config::set_feature_from_constant(ConfigYAML::YAML_USE_FORMS, 'APP_YAML_USE_FORMS', false);


